package uz.pdp;

public interface Response {
    String WRONG_COMMAND = "*** WRONG COMMAND ***";
    String EMPTY = "*** EMPTY ***";
    //For Users
    String ENTER_NAME = "*** ENTER NAME ***";
    String ENTER_PHONE_NUMBER = "*** ENTER PHONE NUMBER ***";
    String ENTER_PASSWORD = "*** ENTER PASSWORD ***";
    String CREATE_PASSWORD = "*** CREATE PASSWORD ***";
    String WRONG_PHONE_NUMBER_OR_PASSWORD = "*** WRONG PHONE NUMBER OR PASSWORD ***";
    String USER_ALREADY_EXISTS = "*** USER ALREADY EXISTS ***";
    String ENTER_SMS_CODE = "*** ENTER SMS CODE ***";
    String WRONG_SMS_CODE = "*** WRONG SMS CODE ***";
    String USER_SUCCESSFULLY_ADDED = "*** USER SUCCESSFULLY ADDED ***";

    //For Categories
    String THERE_IS_NO_CATEGORY = "*** THERE IS NO CATEGORY ***";
    String CATEGORY_NOT_FOUND = "*** CATEGORY NOT FOUND ***";
    String ENTER_CATEGORY_NAME = "*** ENTER CATEGORY NAME ***";
    String CATEGORY_ALREADY_EXISTS = "*** CATEGORY ALREADY EXISTS ***";
    String CATEGORY_SUCCESSFULLY_ADDED = "*** CATEGORY SUCCESSFULLY ADDED ***";
    String CHOOSE_CATEGORY = "*** CHOOSE CATEGORY ***";

    //For Products
    String ENTER_PRODUCT_NAME = "*** ENTER PRODUCT NAME ***";
    String PRODUCT_ALREADY_EXISTS = "*** PRODUCT ALREADY EXISTS ***";
    String PRODUCT_NOT_FOUND = "*** PRODUCT NOT FOUND ***";
    String ENTER_PRODUCT_PRICE = "*** ENTER PRODUCT PRICE ***";
    String ENTER_PRODUCT_DISCOUNT = "*** ENTER PRODUCT DISCOUNT ***";
    String ENTER_PRODUCT_DESCRIPTION = "*** ENTER PRODUCT DESCRIPTION ***";
    String PRODUCT_SUCCESSFULLY_ADDED = "*** PRODUCT SUCCESSFULLY ADDED ***";
    String CHOOSE_PRODUCT = "*** CHOOSE PRODUCT ***";
    String PRODUCT_SUCCESSFULLY_FORMALIZED = "*** PRODUCT SUCCESSFULLY FORMALIZED ***";
    String ENTER_COUNT = "*** ENTER COUNT ***";

    //For Basket
    String PRODUCT_SUCCESSFULLY_ADDED_TO_BASKET = "*** PRODUCT SUCCESSFULLY ADDED TO BASKET ***";
}